application: foojalworld
version: 1
runtime: python
api_version: 1

builtins:
- datastore_admin: on

inbound_services:
- mail

handlers:

- url: /fantasm/.*
  script: fantasm/main.py
  login: admin

- url: /test.*
  script: gaeunit.py
  login: admin
  
- url: /favicon.ico
  static_files: public/images/favicon.ico
  upload: public/images/favicon.ico
      
- url: /public
  static_dir: public

- url: /google_checkout/.*
  script: main.py
  secure: always

- url: /.*
  script: main.py

- url: /_ah/mail/invites.+
  script: mail_handler.py
  login: admin

- url: /_ah/mail/.+
  script: mail_handler.py
  login: admin

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?Clippings.txt
- ^(.*/)?Photo.JPG
- ^(.*/)?.*/test/.*
- ^(.*/)?gaeunit.py

